[package]
name = "kv"
version = "0.2.0"
authors = ["David Briggs <email@dpbriggs.ca>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
dirs = "1.0.4"
clap = "2.32.0"
human-panic = "1.0.1"
tabwriter = "1.1.0"
